using LazyFURS.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace LazyFURS
{
    internal class CompanyManager
    {
        private readonly Dictionary<string, CompanyEntity> companies = new();

        // Country ISO code constants
        //*

        private const string UNITED_STATES_ISO = "US";
        private const string IRELAND_ISO = "IE";
        private const string FINLAND_ISO = "FI";
        private const string SPAIN_ISO = "ES";
        private const string GERMANY_ISO = "DE";
        private const string SWITZERLAND_ISO = "CH";
        private const string UNITED_KINGDOM_ISO = "GB";
        private const string FRANCE_ISO = "FR";
        private const string DENMARK_ISO = "DK";
        private const string NETHERLANDS_ISO = "NL";
        private const string BELGIUM_ISO = "BE";
        private const string LUXEMBOURG_ISO = "LU";
        private const string MEXICO_ISO = "MX";
        private const string BRAZIL_ISO = "BR";
        private const string CHILE_ISO = "CL";
        private const string CANADA_ISO = "CA";
        private const string PERU_ISO = "PE";
        private const string CAYMAN_ISLANDS_ISO = "KY";
        private const string SOUTH_AFRICA_ISO = "ZA";
        private const string COLOMBIA_ISO = "CO";
        private const string ISRAEL_ISO = "IL";
        private const string CHINA_ISO = "CN";
        private const string ITALY_ISO = "IT";
        private const string CYPRUS_ISO = "CY";
        private const string MONACO_ISO = "MC";
        private const string NORWAY_ISO = "NO";
        private const string ARGENTINA_ISO = "AR";
        private const string GREECE_ISO = "GR";
        private const string SINGAPORE_ISO = "SG";
        private const string COSTA_RICA_ISO = "CR";

        public CompanyManager()
        {
            List<CompanyEntity> data =
            [
                new CompanyEntity { ISIN = "US8085247976", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Schwab US Dividend Equity ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CA44054J1012", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Horizons Marijuana Life Sciences Index ETF", TaxReductionText = "10. člen, odstavek 2b" },
                new CompanyEntity { ISIN = "US00162Q4525", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Alerian MLP ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US46434V6213", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "iShares Core Dividend Growth ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4642866085", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "iShares MSCI Eurozone ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4642867497", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "iShares MSCI Switzerland ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4642864007", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Brazil Index MSCI Ishares", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US46434G8226", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Ishares MSCI JAPAN ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4642868065", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "iShares MSCI Germany ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US46434V7385", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "iShares Core MSCI Europe ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4642868149", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "iShares MSCI Netherlands ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4642868222", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "iShares MSCI Mexico ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US78464A6982", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "SPDR S&P Regional Banking ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US9220428745", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Vanguard FTSE Europe ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US81369Y5069", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Energy Select Sector SPDR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US81369Y8865", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Utilities Select Sector SPDR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US25460G6098", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Direxion Daily Energy Bull 2X Shares", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US46429B5984", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "iShares MSCI India ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0758871091", Address = "1 Becton Drive Franklin Lakes, NJ 07417-1880 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Becton Dickinson & Co.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US58933Y1055", Address = "2000 Galloping Hill Road Kenilworth, NJ 07033 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Merck & Co.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "IE00BTN1Y115", Address = "20 On Hatch Lower Hatch Street Dublin 2 Ireland", Country = IRELAND_ISO, Currency = CurrencyType.USD, Name = "Medtronic PLC", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0378331005", Address = "One Apple Park Way Cupertino, CA 95014 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Apple", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0028241000", Address = "100 Abbott Park Road Abbott Park North Chicago, IL 60064-6400 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Abbott Laboratories", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4781601046", Address = "One Johnson & Johnson Plaza New Brunswick, NJ 08933 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Johnson & Johnson", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US5949181045", Address = "One Microsoft Way Redmond, WA 98052-6399 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Microsoft", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US5324571083", Address = "Lilly Corporate Center Indianapolis, IN 46285 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Eli Lilly & Co", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US46434G7723", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "iShares MSCI Taiwan ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US74347Y8883", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "ProShares Ultra Bloomberg Crude Oil", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US6549022043", Address = "Karakaari 7 Espoo, 02610 Finland", Country = FINLAND_ISO, Currency = CurrencyType.USD, Name = "Nokia Oyj", TaxReductionText = "10. člen, odstavek 2b" },
                new CompanyEntity { ISIN = "US09075F1075", Address = "9540 Towne Centre Drive Suite 100 San Diego, CA 92121 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "BioNano Genomics Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US88160R1014", Address = "1 Tesla Road Austin, TX 78725 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Tesla Motors, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US9344231041", Address = "230 Park Avenue South New York, NY 10003 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Warner Bros Discovery Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US70450Y1038", Address = "2211 North First Street San Jose, CA 95131 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "PayPal Holdings", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US19260Q1076", Address = "251 Little Falls Drive Wilmington, DE 19808 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Coinbase Global Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US02079K1079", Address = "1600 Amphitheatre Parkway Mountain View, CA 94043 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Alphabet", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0231351067", Address = "410 Terry Avenue North Seattle, WA 98109-5210 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Amazon.com Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US30303M1027", Address = "1 Meta Way Menlo Park, CA 94025 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Meta Platforms Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US72919P2020", Address = "968 Albany Shaker Road Latham, NY 12110 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Plug Power Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US64110L1061", Address = "121 Albright Way Los Gatos, CA 95032 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Netflix, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US7475251036", Address = "5775 Morehouse Drive San Diego, CA 92121-1714 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Qualcomm Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0079031078", Address = "2485 Augustine Drive Santa Clara, CA 95054 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Advanced Micro Devices Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US00724F1012", Address = "345 Park Avenue San Jose, CA 95110-2704 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Adobe Systems Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US67066G1040", Address = "2788 San Tomas Expressway Santa Clara, CA 95051 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "NVIDIA Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4581401001", Address = "2200 Mission College Boulevard Santa Clara, CA 95054-1549 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Intel", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0090661010", Address = "888 Brannan Street San Francisco, CA 94103 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Airbnb Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "USN070592100", Address = "De Run 6501 Veldhoven 5504 DR Netherlands", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "ASML Holding NV - ADR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US02079K3059", Address = "1600 Amphitheatre Parkway Mountain View, CA 94043 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Alphabet Inc Class A", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US45784P1012", Address = "100 Nagog Park Acton, MA 01720", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Insulet Corp.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "ES0157097017", Address = "Ronda Del General Miter, 151 Barcelona 08022 Spain", Country = SPAIN_ISO, Currency = CurrencyType.EUR, Name = "Laboratorios Almirall SA", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US8753722037", Address = "12400 High Bluff Drive San Diego, CA 92130 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Tandem Diabetes Care Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "DE000BAY0017", Address = "Kaiser-Wilhelm-Allee 1 Leverkusen 51368 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Bayer AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US2521311074", Address = "6340 Sequence Drive San Diego, CA 92121 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "DexCom Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CH0012032048", Address = "Grenzacherstrasse 124 Basel 4058 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.CHF, Name = "Roche Holding Ltd", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "GB0009895292", Address = "1 Francis Crick Avenue Cambridge Biomedical Campus Cambridge CB2 0AA United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.GBX, Name = "AstraZeneca", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "FR0000120578", Address = "54, Rue La BoEtie Paris 75008 France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "Sanofi", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US6701002056", Address = "Novo AllE 1 Bagsvaerd 2880 Denmark", Country = DENMARK_ISO, Currency = CurrencyType.USD, Name = "Novo-Nordisk A/S SPONS ADR", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "DE0007236101", Address = "Werner-von-Siemens-Strasse 1 Munich 80333 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Siemens Aktiengesellschaft", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "DE0006231004", Address = "Am Campeon 1-15 Neubiberg 85579 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Infineon Technologies AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US66987V1098", Address = "Lichtstrasse 35 Basel 4056 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.USD, Name = "Novartis ADR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "GB0007980591", Address = "1 St James's Square London SW1Y 4PD United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.GBX, Name = "BP", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "IE000S9YS762", Address = "Forge, 43 Church Street West Woking, GU21 6HT United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.USD, Name = "Linde PLC", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "GB00BP6MXD84", Address = "Shell Centre, 2 York Road London SE1 7NA United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.GBX, Name = "Shell PLC", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "CH0012221716", Address = "Affolternstrasse 44 Zurich 8050 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.CHF, Name = "ABB LTD", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "FR0000120271", Address = "2, place Jean Millier La DEfense 6 Courbevoie 92078 France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "TotalEnergies SE", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "NL0009538784", Address = "High Tech Campus 60 Eindhoven 5656 AG Netherlands", Country = NETHERLANDS_ISO, Currency = CurrencyType.USD, Name = "NXP Semiconductors", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CH0044328745", Address = "Baerengasse 32 Zurich 8001 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.USD, Name = "Chubb Corp", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "DE0005557508", Address = "Friedrich-Ebert-Allee 140 Bonn 53113 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Deutsche Telekom AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CH0011075394", Address = "Mythenquai 2 Zurich 8002 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.CHF, Name = "Zurich Insurance Group Ltd", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CH0038863350", Address = "Avenue Nestlé 55 Vevey 1800 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.CHF, Name = "Nestle SA", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CH0244767585", Address = "Bahnhofstrasse 45 P.O. Box Zurich 8001 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.CHF, Name = "UBS Group AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "NL0000235190", Address = "Mendelweg 30 Leiden 2333 CS Netherlands", Country = NETHERLANDS_ISO, Currency = CurrencyType.EUR, Name = "AIRBUS SE", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "FR0000121014", Address = "22, Avenue Montaigne Paris 75008 France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "LVMH Moet Hennessy Louis Vuitton SA", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "NL00150001Q9", Address = "Giorgio Fossati Taurusavenue 1 Hoofddorp 2132 LS Netherlands", Country = NETHERLANDS_ISO, Currency = CurrencyType.USD, Name = "Stellantis NV", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "ES0148396007", Address = "Edificio Inditex Avenida de la DiputaciOn s/n Arteixo Corunna 15143 Spain", Country = SPAIN_ISO, Currency = CurrencyType.EUR, Name = "Industria de Diseno Textil SA", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "DE000BASF111", Address = "Carl-Bosch-Strasse 38 Ludwigshafen am Rhein 67056 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "BASF SE", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "DE0007100000", Address = "Mercedesstrasse 120 Stuttgart 70372 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Mercedes-Benz Group AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US05964H1059", Address = "Santander Group City Av. de Cantabria s/n Boadilla del Monte Madrid 28660 Spain", Country = SPAIN_ISO, Currency = CurrencyType.USD, Name = "Banco Santander SA (US)-ADR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "BE0974293251", Address = "Brouwerijplein 1 Leuven 3000 Belgium", Country = BELGIUM_ISO, Currency = CurrencyType.EUR, Name = "Anheuser Busch InBev", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "FR0000121485", Address = "40 rue de SEvres Paris 75007 France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "Kering SA", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "NL0011821202", Address = "Bijlmerdreef 106 Amsterdam 1102 CT Netherlands", Country = NETHERLANDS_ISO, Currency = CurrencyType.EUR, Name = "ING Groep NV", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "DE0008404005", Address = "KOeniginstrasse 28 Munich 80802 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Allianz SE", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "FR0000120628", Address = "25, avenue Matignon Paris 75008 France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "AXA Group", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "DE0005552004", Address = "Platz der Deutschen Post Bonn 53113 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Deutsche Post AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "NL0010273215", Address = "De Run 6501 Veldhoven 5504 DR Netherlands", Country = NETHERLANDS_ISO, Currency = CurrencyType.USD, Name = "ASML Holding NV", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US8808901081", Address = "26 Boulevard Royal 4th Floor Luxembourg City 2449 Luxembourg", Country = LUXEMBOURG_ISO, Currency = CurrencyType.USD, Name = "Ternium SA-ADR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US3444191064", Address = "General Anaya Nº 601 Pte. Col. Bella Vista Monterrey, NL 64410 Mexico", Country = MEXICO_ISO, Currency = CurrencyType.USD, Name = "Fomento Economico Mexicano SAB-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "LU0584671464", Address = "Vertigo Naos Building 6, Rue EugEne Ruppert Luxembourg City 2453 Luxembourg", Country = LUXEMBOURG_ISO, Currency = CurrencyType.USD, Name = "Adecoagro S.A.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "DE000A1EWWW0", Address = "Adi-Dassler-Strasse 1 Herzogenaurach 91074 Germany", Country = GERMANY_ISO, Currency = CurrencyType.USD, Name = "Adidas AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "DE0007664039", Address = "Berliner Ring 2 Wolfsburg 38440 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Volkswagen AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "FR0000120073", Address = "75 quai d'Orsay cedex 07 Paris 75321 France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "Air Liquide SA", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "FR0000121972", Address = "35 rue Joseph Monier Rueil-Malmaison 92506 France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "Schneider Electric SE", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US86959K1051", Address = "Av. Professor MagalhAes Neto, 1,752 10th Floor Rooms 1010 and 1011 Salvador, BA 41810-012 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Suzano SA-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "DE0007164600", Address = "Dietmar-Hopp-Allee 16 Walldorf 69190 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "SAP SE", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US05967A1079", Address = "Banco Santander (Brasil) SA Avenida Juscelino Kubitschek 2235 & 2041, Bloco A Vila Olímpia Sao Paulo, Sao Paulo 04543-011 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Banco Santander Brasil SA", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US2044096012", Address = "Avenida Barbacena, 1200 Belo Horizonte, MG 30190-131 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Companhia Energetica de Minas Gerais-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "FR0000131104", Address = "16 boulevard des Italiens Paris 75009 France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "BNP Paribas SA", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US8336351056", Address = "El Trovador 4285 6th Floor Las Condes Santiago de Chile Chile", Country = CHILE_ISO, Currency = CurrencyType.USD, Name = "Sociedad Quimica y Minera de Chile SA-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US84265V1052", Address = "1440 East Missouri Avenue Suite 160 Phoenix, AZ 85014 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Southern Copper Corp", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US20440W1053", Address = "Av. Brigadeiro Faria Lima, 3400 19th and 20th Floors Itaim Bibi Sao Paulo, SP 04538-132 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Cia Siderurgica Nacional SA-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US3737371050", Address = "Av. Dra. Ruth Cardoso, 8,501 8° andar Sao Paulo, SP 05425-070 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Gerdau SA-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "CA9628791027", Address = "1021 West Hastings Street Suite 3500 Vancouver, BC V6E 0C3 Canada", Country = CANADA_ISO, Currency = CurrencyType.USD, Name = "Wheaton Precious Metals Corp", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US0594603039", Address = "Cidade De Deus, S/N Vila Yara Osasco, SP 06029-900 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Banco Bradesco ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "BMG2519Y1084", Address = "Calle Centenario 156 La Molina Lima 12 Peru", Country = PERU_ISO, Currency = CurrencyType.USD, Name = "Credicorp Ltd", TaxReductionText = "" },
                new CompanyEntity { ISIN = "PR3186727065", Address = "1519 Ponce de Leon Ave. Stop 23 PO Box 9146 San Juan, PR 00908-0146 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "First BanCorp/Puerto Rico", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4655621062", Address = "PraCa Alfredo Egydio de Souza Aranha 100 Sao Paulo, SP 04344-902 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Itau Unibanco Holding ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "ES0144580Y14", Address = "Plaza Euskadi 5 Bilbao 48009 Spain", Country = SPAIN_ISO, Currency = CurrencyType.EUR, Name = "Iberdrola", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US71654V1017", Address = "Avenida RepUblica do Chile, 65 Centro Rio De Janeiro, RJ 20031-912 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Petroleo Brasileiro ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "PR7331747001", Address = "209 MuNoz Rivera Avenue Hato Rey, PR 00918 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Popular Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US20441A1025", Address = "Rua Costa Carvalho, 300 Sao Paulo, SP 05429-900 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Cia de Saneamento Basico do Estado de Sao Paulo-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "CA98462Y1007", Address = "Royal Bank Plaza Suite 2200 North Tower 200 Bay Street Toronto, ON M5J 2J3 Canada", Country = CANADA_ISO, Currency = CurrencyType.USD, Name = "Yamana Gold Inc", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US02390A1016", Address = "Lago Zurich 245 Plaza Carso / Edificio Telcel, Piso 16 Colonia Ampliación Granada Miguel Hidalgo Mexico City, DF 11529 Mexico", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "America Movil, S.A.B. de C.V.-ADR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US91912E1055", Address = "Praia de Botafogo 186 Salas 501 a 1901 18 andar Botafogo Rio De Janeiro, RJ 22250-145 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Vale SA-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US15234Q2075", Address = "Rua da Quitanda, 196 9th Floor Centro Rio De Janeiro, RJ 20091-005 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Centrais Eletricas Brasileiras - ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "CH0210483332", Address = "50, chemin de la Chênaie CP30 Bellevue 1293 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.CHF, Name = "Compagnie Financiere Richemont SA", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US87936R2058", Address = "Av. Engenheiro Luis Carlos Berrini 1376,32º andar Sao Paulo, SP 04571-936 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Telefônica Brasil SA-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "GB0001383545", Address = "ETF", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.GBP, Name = "UK100 Index", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "ES0113900J37", Address = "Santander Group City Av. de Cantabria s/n Boadilla del Monte Madrid 28660 Spain ", Country = SPAIN_ISO, Currency = CurrencyType.EUR, Name = "Banco Santander SA", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "FI0009000681", Address = "Karakaari 7 Espoo 02610 Finland", Country = FINLAND_ISO, Currency = CurrencyType.EUR, Name = "Nokia Corp.", TaxReductionText = "10. clen, odstavek 1b" },
                new CompanyEntity { ISIN = "ES0173516115", Address = "Repsol Campus C/ Mendez Alvaro, 44 Madrid 28045 Spain", Country = SPAIN_ISO, Currency = CurrencyType.EUR, Name = "Repsol", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "GB00BN7SWP63", Address = "980 Great West Road Middlesex Brentford TW8 9GS United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.GBX, Name = "GlaxoSmithKline", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "DE0005190003", Address = "Petuelring 130 Munich 80809 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Bayerische Motoren Werke Aktiengesellschaft", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "FR0000125486", Address = "1973 boulevard de la Défense CS 10268 Cedex Nanterre 92757 France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "Vinci S.A", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "DE0008430026", Address = "Königinstr. 107 Munich 80802 Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Muenchener Rueckvrschrng Gslchft AG Mnch", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CH0418792922", Address = "Zugerstrasse 50 Baar 6340 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.CHF, Name = "Sika Ltd", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "NL0000226223", Address = "WTC Schiphol Airport Schiphol, Noord-Holland 1118 BH Netherlands", Country = NETHERLANDS_ISO, Currency = CurrencyType.EUR, Name = "STMicroelectronics Company", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US63884N1081", Address = "Avenida Alexandre Colares No. 1188, Sala A17-Bloco A Parque Anhanguera Sao Paulo, SP 05106-000 Brazil", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Natura & Co Holding SA-ADR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "KYG851581069", Address = "Harbour Place 4th Floor 103 South Church Street PO Box 10240 George Town KY1-1002 Cayman Islands", Country = CAYMAN_ISLANDS_ISO, Currency = CurrencyType.USD, Name = "StoneCo Ltd A", TaxReductionText = "" },
                new CompanyEntity { ISIN = "KYG6683N1034", Address = "Rua Capote Valente, 39 Sao Paulo, SP 5409-0000 Brazil ", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Nu Holdings Ltd.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US58733R1023", Address = "WTC Free Zone Dr. Luis Bonavita 1294 Of. 1733 Tower II Montevideo 11300 Uruguay", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "MercadoLibre", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US40049J2069", Address = "Av. Vasco de Quiroga 2000 Building A Floor 4,Delegación Alvaro Obregón Col. Santa Fe Mexico City, DF 12210 Mexico", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Grupo Televisa, S.A.B.-ADR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "KYG290181018", Address = "Dr. Luis Bonavita 1294 Montevideo 11300 Uruguay", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "dLocal Ltd.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US38045R2067", Address = "Praca Comandante Linneu Gomes, S/N Portaria 3, prEdio 24 Jardim Aeroporto Sao Paulo, SP 04626-020 Brazil", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Gol Linhas Aereas Inteligentes SA-ADR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US25490K5965", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Direxion Shares Etf Trust-Direxion Daily Homebuilders & Supplies Bull 3x Shares", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US82575P1075", Address = "Constantia Office Park Cnr 14th Ave & Hendrik Potgieter Rd, 1709, Weltevreden Park, South Africa", Country = SOUTH_AFRICA_ISO, Currency = CurrencyType.USD, Name = "Sibanye Stillwater Ltd-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US8552441094", Address = "2401 Utah Avenue South Seattle, WA 98134 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Starbucks Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US7134481081", Address = "700 Anderson Hill Road Purchase, NY 10577 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "PepsiCo", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US60770K1079", Address = "200 Technology Square Cambridge, MA 02139 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Moderna Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "NL0012969182", Address = "Simon Carmiggeltstraat 6-50 Amsterdam, 1011 DJ Netherlands", Country = NETHERLANDS_ISO, Currency = CurrencyType.EUR, Name = "Adyen NV", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "KYG982391099", Address = "20, Genesis Close George Town Grand Cayman KY-1-1208 Cayman Islands", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "XP Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US1512908898", Address = "Avenida Ricardo Margáin Zozaya #325 Colonia Valle del Campestre San Pedro Garza García, NL 66265 Mexico", Country = MEXICO_ISO, Currency = CurrencyType.USD, Name = "Cemex, S.A.B. de C.V.-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US10552T1079", Address = "Av. Das NaCOes Unidas 14.401 22nd to 25th Floors Torre JequitibA CondomInio Parque da Cid ChAcara Santo AntOnio Sao Paulo, SP 04730-090 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "BRF SA-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US29082A1079", Address = "Eldorado Business Tower 30th floor Avenida Dra. Ruth Cardoso, No. 8,501 Pinheiros Sao Paulo, SP 05425-070 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Embraer SA-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "KYG687071012", Address = "Avenida Brigadeiro Faria Lima, 1384 4º andar Parte A Sao Paulo, SP 01451-001 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Pagseguro Digital Ltd", TaxReductionText = "" },
                new CompanyEntity { ISIN = "LU0974299876", Address = "37A Avenue J.F. Kennedy Luxembourg City, 1855 Luxembourg", Country = LUXEMBOURG_ISO, Currency = CurrencyType.USD, Name = "Globant SA", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US02319V1035", Address = "Rua Dr. Renato Paes de Barros, 1017 3rd Floor Sao Paulo, SP 04530-001 Brazil", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Ambev ADR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US05501U1060", Address = "Av. Marcos Penteado de Ulhôa Rodrigues n. 939, 8th floor Edifício Jatobá CondomA-nio Castelo Branco Office Park Tamboré Barueri, SP Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Azul SA-ADR", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US88688T1007", Address = "265 Talbot Street West Leamington, ON N8H 5L4 Canada", Country = CANADA_ISO, Currency = CurrencyType.USD, Name = "Tilray Brands Inc", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "PAP310761054", Address = "Boulevard Costa del Este Av. Principal y Av. de la Rotonda UrbanizaciOn Costa del Este Complejo Business Park,Torre Norte, Parq Panama City 0816-06819 Panama", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Copa Holdings SA", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "DE0007037129", Address = "Zugerstrasse 50 Baar 6340 Switzerland", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "RWE AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CH0013841017", Address = "Muenchensteinerstrasse 38 Basel 4002 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.CHF, Name = "Lonza Group Ltd", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CH1169360919", Address = "Bruggerstrasse 71a Baden 5400 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.CHF, Name = "Accelleron Industries Ltd", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US1101221083", Address = "Route 206 & Province Line Road Princeton, NY 08543 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Bristol-Myers Squibb Co", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US9229085538", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Vanguard Real Estate ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "KYG872641009", Address = "Av. Circunvalar a 100 mts de la Via 40 Barrio Las Flores Barranquilla, 33142 Colombia", Country = COLOMBIA_ISO, Currency = CurrencyType.USD, Name = "Tecnoglass Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US92837L1098", Address = "Pedregal 24, Floor 4 Mexico City, DF 11040 Mexico", Country = MEXICO_ISO, Currency = CurrencyType.USD, Name = "Vista Energy SAB de CV", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US9842451000", Address = "Macacha GUeemes 515,Ciudad Autonoma de,Buenos Aires, C1106BKK", Country = ARGENTINA_ISO, Currency = CurrencyType.USD, Name = "YPF Sociedad Anónima", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US81689T1043", Address = "Avenida Ayrton Senna, No. 6,000 Rio De Janeiro, 22775-005 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Sendas Distribuidora SA", TaxReductionText = "" },
                new CompanyEntity { ISIN = "CA8265991023", Address = "Avenida Nove de Julho 4939, 9th Floor, Office 84 São Paulo, SP 01407-200 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Sigma Lithium Corporation", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US05464C1018", Address = "17800 North 85th Street Scottsdale, Arizona 85255 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Axon Enterprise Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "FR0000120644", Address = "17, Boulevard Haussmann Paris, 75009 France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "Danone S.A", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US1280302027", Address = "1052 Highland Colony Parkway, Suite 200 Ridgeland, Mississippi 39157 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Cal-Maine Foods, Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "IL0065100930", Address = "9 Andrei Sakharov Street, PO Box 15067 Haifa, 3190500 Israel", Country = ISRAEL_ISO, Currency = CurrencyType.USD, Name = "ZIM Shipping Services Ltd", TaxReductionText = "10. clen, odstavek 2c" },
                new CompanyEntity { ISIN = "GB0031743007", Address = "Horseferry House London, SW1P 2AW United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.GBX, Name = "Burberry Group", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "GB0005405286", Address = "8 Canada Square London, E14 5HQ United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.GBX, Name = "HSBC Holdings", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "GB0000811801", Address = "Barratt House Coalville, LE67 1UF United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.GBX, Name = "Barratt Redrow PLC", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US4005011022", Address = "Plaza Metrópoli Patriotismo, Piso 5, Av. Patriotismo 201 Mexico City, DF 03800 Mexico", Country = MEXICO_ISO, Currency = CurrencyType.USD, Name = "Grupo Aeroportuario del Centro Norte S.A.B. de C.V.", TaxReductionText = "10. clen, odstavek 2" },
                new CompanyEntity { ISIN = "US01609W1027", Address = "969 West Wen Yi Road, Yu Hang District Hangzhou, 311121 China", Country = CHINA_ISO, Currency = CurrencyType.USD, Name = "Alibaba-ADR", TaxReductionText = "10. clen, odstavek 2" },
                new CompanyEntity { ISIN = "IE00BGSF1X88", Address = "Bond", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "iShares $ Treasury Bond 0-1yr UCITS ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US2546871060", Address = "500 South Buena Vista Street Burbank, California 91521 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Walt Disney", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US7999261008", Address = "Forum 1 Basel, 4056 Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.USD, Name = "Sandoz Group AG-ADR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US11135F1012", Address = "3421 Hillview Ave Palo Alto, California 94304 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Broadcom Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US22788C1053", Address = "206 East 9th Street, Suite 1400 Austin, Texas 78701 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Crowdstrike Holdings", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US02376R1023", Address = "1 Skyview Drive Fort Worth, Texas 76155 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Anglo American", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "NL0011585146", Address = "Via Abetone Inferiore n. 4 Maranello, Missouri 41053 Italy", Country = ITALY_ISO, Currency = CurrencyType.USD, Name = "Ferrari NV", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "IT0000072618", Address = "Piazza San Carlo, 156 Turin, 10121 Italy", Country = ITALY_ISO, Currency = CurrencyType.EUR, Name = "Intesa Sanpaolo Group", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "IT0005239360", Address = "Tower A Milan, 20154 Italy", Country = ITALY_ISO, Currency = CurrencyType.EUR, Name = "UniCredit Commercial Bank", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "LU1778762911", Address = "5, Place de la Gare Luxembourg, 1616 Luxembourg", Country = LUXEMBOURG_ISO, Currency = CurrencyType.USD, Name = "Spotify Technologies SA", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0420682058", Address = "110 Fulbourn Road Cambridge, CB1 9NJ United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.USD, Name = "ARM Holdings PLC", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US46138E3541", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Invesco S&P 500 Low Volatility", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US5288723027", Address = "2445 Technology Forest Boulevard, 11th Floor The Woodlands, Texas 77381 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Lexicon Pharmaceuticals Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US40637H1095", Address = "12390 El Camino Real San Diego, California 92130 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Halozyme Therapeutics Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US56400P7069", Address = "1 Casper Street Danbury, Connecticut 06810 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "MannKind Corp", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "IT0003128367", Address = "Viale Regina Margherita, 137 Rome, 00198 Italy", Country = ITALY_ISO, Currency = CurrencyType.EUR, Name = "Enel Power Company", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "IT0003132476", Address = "Piazzale Enrico Mattei 1 Rome, 00144 Italy", Country = ITALY_ISO, Currency = CurrencyType.EUR, Name = "Eni Energy Company", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US37733W2044", Address = "980 Great West Road, Middlesex Brentford, TW8 9GS United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.USD, Name = "GlaxoSmithKline plc ADR", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "IE0001827041", Address = "Stonemason’s Way, Rathfarnham Dublin, 16 Ireland", Country = IRELAND_ISO, Currency = CurrencyType.GBX, Name = "CRH plc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US88706T1088", Address = "JoAo Cabral de Melo Neto Avenue, 850 North Tower Rio De Janeiro, RJ 22775-057 Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "TIM SA", TaxReductionText = "" },
                new CompanyEntity { ISIN = "JE00BJVNSS43", Address = "751 Lakefront Commons Newport News, Virginia 23606 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.GBX, Name = "Ferguson PLC", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CY0200352116", Address = "Iris House, 8, John Kennedy Street Limassol, 3106 Cyprus", Country = CYPRUS_ISO, Currency = CurrencyType.USD, Name = "Frontline PLC", TaxReductionText = "10. clen, odstavek 2" },
                new CompanyEntity { ISIN = "CA15135U1093", Address = "4100, 225 – 6 Avenue SW, PO Box 766 Calgary, AB T2P 0M5 Canada", Country = CANADA_ISO, Currency = CurrencyType.USD, Name = "Cenovus Energy Inc", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US81369Y8527", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Communication Services Select Sector SPDR Fund", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US81369Y4070", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Consumer Discret Select Sector SPDR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "MHY7542C1306", Address = "99 Boulevard du Jardin Exotique Monaco, 98000 Monaco", Country = MONACO_ISO, Currency = CurrencyType.USD, Name = "Scorpio Tankers Inc", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US46090E1038", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Invesco QQQ", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US6516391066", Address = "6900 E Layton Avenue, Suite 700 Denver, Colorado 80237 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Newmont Mining Corp", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US24665A1034", Address = "310 Seven Springs Way, Suite 400 and 500 Brentwood, Tennessee 37027 United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Delek US Holdings Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US81369Y6059", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Financial Select Sector SPDR", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US81369Y1001", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Materials Select Sector SPDR ", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US78467X1090", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "SPDR Dow Jones Industrial Average ETF Trust ", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4642876555", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Ishares Russell 2000 ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "NO0003921009", Address = "Dokkveien 1 Oslo, 0250 Norway", Country = NORWAY_ISO, Currency = CurrencyType.NOK, Name = "DNO ASA", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US6092071058", Address = "905 West Fulton Market,Suite 200,Chicago, IL 60607,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Mondelez International, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US5951121038", Address = "8000 South Federal Way,Boise, ID 83716-9632,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Micron Technology, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US05961W1053", Address = "Avenida Eduardo Madero 1172,Buenos Aires, C1106ACY,Argentina", Country = ARGENTINA_ISO, Currency = CurrencyType.USD, Name = "Banco Macro S.A.", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US9229083632", Address = "ETF", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Vanguard S&P 500 ETF", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US2044481040", Address = "Las Begonias 415,19th floor San Isidro,Lima, 27,Peru", Country = PERU_ISO, Currency = CurrencyType.USD, Name = "Compañía de Minas Buenaventura S.A.A.", TaxReductionText = "" },
                new CompanyEntity { ISIN = "MHY641771016", Address = "Ethnarchou Makariou Ave.,& 2 D. Falireos St.,Neo Faliro, 185 47,Greece", Country = GREECE_ISO, Currency = CurrencyType.NOK, Name = "Okeanis Eco Tankers Corp.", TaxReductionText = "10. clen, odstavek 2" },
                new CompanyEntity { ISIN = "US5801351017", Address = "110 North Carpenter Street,Chicago, IL 60607,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "McDonald's Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US1912161007", Address = "One Coca-Cola Plaza,Atlanta, GA 30313,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "The Coca-Cola Company", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CA4969024047", Address = "25 York Street,17th Floor,Toronto, ON M5J 2V5,Canada", Country = CANADA_ISO, Currency = CurrencyType.CAD, Name = "Kinross Gold Corporation", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "NL0009434992", Address = "Williams Tower,2800 Post Oak Blvd Suite 5100,Houston, TX 77056,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "LyondellBasell Industries N.V.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CA0115321089", Address = "Brookfield Place,181 Bay Street Suite 3910,Toronto, ON M5J 2T3,Canada", Country = CANADA_ISO, Currency = CurrencyType.CAD, Name = "Alamos Gold Inc.", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "CH0102484968", Address = "Bahnhofstrasse 36,Zurich, 8010,Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.CHF, Name = "Julius Bär Gruppe AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CA0585861085", Address = "9000 Glenlyon Parkway,Burnaby, BC V5J 5J8,Canada", Country = CANADA_ISO, Currency = CurrencyType.CAD, Name = "Ballard Power Systems Inc.", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US44951W1062", Address = "13131 Dairy Ashford Rd,Suite 500,Sugar Land, TX 77478,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "IES Holdings, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US34959E1091", Address = "909 Kifer Road,Sunnyvale, CA 94086,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Fortinet, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US3906071093", Address = "9811 Katy Freeway,Suite 1200,Houston, TX 77024,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Great Lakes Dredge & Dock Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US20030N1019", Address = "One Comcast Center,Philadelphia, PA 19103-2838,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Comcast Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "FR0014004L86", Address = "9, Rond-Point des Champs-ElysEes,Marcel Dassault,Paris, 75008,France", Country =FRANCE_ISO, Currency = CurrencyType.EUR, Name = "Dassault Aviation société anonyme", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US74623V1035", Address = "20 North Orange Avenue,Suite 106,Orlando, FL 32801,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "PureCycle Technologies, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US40131M1099", Address = "3100 Hanover Street,Palo Alto, CA 94304,United States", Country =UNITED_STATES_ISO , Currency = CurrencyType.USD, Name = "Guardant Health, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "BMG9456A1009", Address = "S.E. Pearman Building,2nd Floor 9 Par-la-Ville Road,Hamilton, HM 11,Bermuda", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.USD, Name = "Golar LNG Limited", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US83406F1021", Address = "234 1st Street,San Francisco, CA 94105,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "SoFi Technologies, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US8592411016", Address = "1800 Hughes Landing Boulevard,Suite 250,The Woodlands, TX 77380,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Sterling Infrastructure, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US55826T1025", Address = "Two Pennsylvania Plaza,New York, NY 10121,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Sphere Entertainment Co.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US76954A1034", Address = "14600 Myford Road,Irvine, CA 92606,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Rivian Automotive, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US30214U1025", Address = "149 Commonwealth Drive,Menlo Park, CA 94025,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Exponent, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US5500211090", Address = "1818 Cornwall Avenue,Vancouver, BC V6J 1C7,Canada", Country = CANADA_ISO, Currency = CurrencyType.USD, Name = "lululemon athletica inc.", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US8825081040", Address = "12500 TI Boulevard,Dallas, TX 75243,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Texas Instruments Incorporated", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US68404L2016", Address = "2200 Mission College Boulevard,Santa Clara, CA 95054-1549,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Intel Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US70614W1009", Address = "441 Ninth Avenue,Sixth Floor,New York, NY 10001,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Peloton Interactive, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CA8849038085", Address = "19 Duncan Street,Toronto, ON M5H 3H1,Canada", Country = CANADA_ISO, Currency = CurrencyType.CAD, Name = "Thomson Reuters Corporation", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US12769G1004", Address = "100 West Liberty Street,12th Floor,Reno, NV 89501,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Caesars Entertainment, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US95058W1009", Address = "One Dave Thomas Boulevard,Dublin, OH 43017,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "The Wendy's Company", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US26142V1052", Address = "222 Berkeley Street,5th Floor,Boston, MA 02116,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "DraftKings Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US09075V1026", Address = "An der Goldgrube 12,55131 Mainz,Germany ", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "BioNTech SE", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US65481N1000", Address = "No.1 Building,No. 195 Huilongguan East Road Changping District,Beijing, 102208,China", Country = CHINA_ISO , Currency = CurrencyType.USD, Name = "Niu Technologies", TaxReductionText = "10. clen, odstavek 2" },
                new CompanyEntity { ISIN = "CA83307B1013", Address = "919–11 Avenue SW,Suite 300,Calgary, AB T2R 1P3,Canada", Country = CANADA_ISO, Currency = CurrencyType.USD, Name = "SNDL Inc.", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US1844991018", Address = "4675 MacArthur Court,Suite 800,Newport Beach, CA 92660,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Clean Energy Fuels Corp.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US2270461096", Address = "Building 5,500 Eldorado Boulevard,Broomfield, CO 80021,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Crocs, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US04010L1035", Address = "1800 Avenue of the Stars,Suite 1400,Los Angeles, CA 90067-4733,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Ares Capital Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US53263P1057", Address = "797 Commonwealth Drive,Warrendale, PA 15086,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Limbach Holdings, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US30161N1019", Address = "10 South Dearborn Street,54th Floor PO Box 805398,Chicago, IL 60680-5379,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Exelon Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US8334451098", Address = "106 East Babcock Street,Suite 3A,Bozeman, MT 59715,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Snowflake Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US9100471096", Address = "233 South Wacker Drive,Chicago, IL 60606,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "United Airlines Holdings, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US47215P1066", Address = "Building A, 20th Floor,No. 18 Kechuang 11 Street Yizhuang Eco & Tech Dev Zn Daxing District,Beijing, 101111,China", Country = CHINA_ISO, Currency = CurrencyType.USD, Name = "JD.com, Inc.", TaxReductionText = "10. clen, odstavek 2" },
                new CompanyEntity { ISIN = "US5719032022", Address = "7750 Wisconsin Avenue,Bethesda, MD 20814,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Marriott International, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US5007541064", Address = "One PPG Place,Pittsburgh, PA 15222,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "The Kraft Heinz Company", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US7504911022", Address = "1510 Cotner Avenue,Los Angeles, CA 90025,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "RadNet, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "KYG386441037", Address = "4388 Shirley Avenue,El Monte, CA 91731,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "GigaCloud Technology Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "KYG4124C1096", Address = "3 Media Close, No. 01-03/06,Singapore, 138498,Singapore", Country = SINGAPORE_ISO, Currency = CurrencyType.USD, Name = "Grab Holdings Limited", TaxReductionText = "10. clen, odstavek 2" },
                new CompanyEntity { ISIN = "US1729081059", Address = "6800 Cintas Boulevard,P.O. Box 625737,Cincinnati, OH 45262-5737,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Cintas Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US3377381088", Address = "255 Fiserv Drive, Brookfield, Wisconsin 53045, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Fiserv, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US8725901040", Address = "12920 SE 38th Street,Bellevue, WA 98006-1350,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "T-Mobile US, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US7223041028", Address = "28th Floor, No. 533 Loushanguan Road, Shanghai, Shanghai, 200051, China", Country = CHINA_ISO, Currency = CurrencyType.EUR, Name = "Pinduoduo Inc", TaxReductionText = "10. clen, odstavek 2" },
                new CompanyEntity { ISIN = "US55087P1049", Address = "185 Berry Street,Suite 400,San Francisco, CA 94107,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Lyft, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US14888U1016", Address = "355 Alhambra Circle,Suite 801,Coral Gables, FL 33134,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Catalyst Pharmaceuticals, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4005061019", Address = "Avenida Mariano Otero No. 1249-B,Torre PacIfico Piso 6 Col. Rinconada del Bosque,Guadalajara, JA 44530,Mexico", Country = MEXICO_ISO, Currency = CurrencyType.USD, Name = "Grupo Aeroportuario del Pacífico, S.A.B. de C.V.", TaxReductionText = "" },
                new CompanyEntity { ISIN = "VGG312491084", Address = "Building B23 and B25,Coyol Free Zone,Alajuela,Costa Rica", Country = COSTA_RICA_ISO, Currency = CurrencyType.USD, Name = "Establishment Labs Holdings Inc.", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US20441B7047", Address = "Rua José Izidoro Biazetto, 158,Bloco A,Curitiba, PR 81200-240,Brazil", Country = BRAZIL_ISO, Currency = CurrencyType.USD, Name = "Companhia Paranaense de Energia", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US40054A1088", Address = "Reconquista 330,Buenos Aires, C1003ABG,Argentina", Country = ARGENTINA_ISO, Currency = CurrencyType.USD, Name = "Grupo Supervielle S.A.", TaxReductionText = "" },
                new CompanyEntity { ISIN = "DE000ENER6Y0", Address = "Otto-Hahn-Ring 6,Munich, 81739,Germany", Country = GERMANY_ISO, Currency = CurrencyType.EUR, Name = "Siemens Energy AG", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "GB0031348658", Address = "1 Churchill Place,London, E14 5HP,United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.GBX, Name = "Barclays PLC", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "FR0010208488", Address = "Tour T1,1 place Samuel de Champlain Faubourg de l’Arche,Courbevoie, 92930,France", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "Engie SA", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US55303J1060", Address = "100 Commercial Street,PO Box 130,Atchison, KS 66002,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "MGP Ingredients, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US46120E6023", Address = "1020 Kifer Road,Sunnyvale, CA 94086-5304,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Intuitive Surgical, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0326541051", Address = "One Analog Way,Wilmington, MA 01887,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Analog Devices, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US67103H1077", Address = "233 South Patterson Avenue,Springfield, MO 65802-2298,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "O'Reilly Automotive, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4612021034", Address = "2700 Coast Avenue,Mountain View, CA 94043,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Intuit Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US64110W1027", Address = "NetEase Building,No. 599 Wangshang Road Binjiang District,Hangzhou, 310052,China", Country = CHINA_ISO, Currency = CurrencyType.USD, Name = "NetEase, Inc.", TaxReductionText = "10. clen, odstavek 2" },
                new CompanyEntity { ISIN = "US0311621009", Address = "One Amgen Center Drive,Thousand Oaks, CA 91320-1799,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Amgen Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US72651A2078", Address = "333 Clay Street,Suite 1600,Houston, TX 77002,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Plains GP Holdings, L.P.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "IE00BLNN3691", Address = "2000 St. James Place,Houston, TX 77056,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Weatherford International plc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US21037T1097", Address = "1310 Point Street,Baltimore, MD 21231-3380,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Constellation Energy Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4385161066", Address = "855 South Mint Street,Charlotte, NC 28202,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Honeywell International Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US7265031051", Address = "333 Clay Street,Suite 1600,Houston, TX 77002,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Plains All American Pipeline, L.P.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US6323071042", Address = "13011 McCallen Pass,Building A Suite 100,Austin, TX 78753,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Natera, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US98389B1008", Address = "414 Nicollet Mall,Minneapolis, MN 55401,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Xcel Energy Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US12572Q1058", Address = "20 South Wacker Drive,Chicago, IL 60606,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "CME Group Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US3789735079", Address = "1351 Holiday Square Boulevard,Covington, LA 70433,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Globalstar, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US63008G2030", Address = "300 5th Avenue,Suite 1010,Waltham, MA 02451,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Nano Dimension Ltd.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US15118V2079", Address = "2381 NW Executive Center Drive,Boca Raton, FL 33431,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Celsius Holdings, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0545402085", Address = "108 Cherry Hill Drive,Beverly, MA 01915-1088,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Axcelis Technologies, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0463531089", Address = "1 Francis Crick Avenue,Cambridge Biomedical Campus,Cambridge, CB2 0AA,United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.USD, Name = "AstraZeneca PLC", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US7034811015", Address = "10713 West Sam Houston Parkway North,Suite 800,Houston, TX 77064,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Patterson-UTI Energy, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0255371017", Address = "1 Riverside Plaza,Columbus, OH 43215-2373,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "American Electric Power Company, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US69181V1070", Address = "Eight Sound Shore Drive,Suite 255,Greenwich, CT 06830-7254,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Oxford Square Capital Corp.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0382221051", Address = "3050 Bowers Avenue,P.O. Box 58039,Santa Clara, CA 95052-8039,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Applied Materials, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US5949724083", Address = "1850 Towers Crescent Plaza,Tysons Corner, VA 22182,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Strategy Inc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US3119001044", Address = "2001 Theurer Boulevard,Winona, MN 55987-1500,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Fastenal Company", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "JE00B4T3BW64", Address = "Baarermattstrasse 3,Baar, 6340,Switzerland", Country = SWITZERLAND_ISO, Currency = CurrencyType.GBX, Name = "Glencore plc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US7707001027", Address = "85 Willow Road,Menlo Park, CA 94025,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Robinhood Markets, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US80105N1054", Address = "46, avenue de la Grande Armée,Paris, 75017,France", Country = FRANCE_ISO, Currency = CurrencyType.USD, Name = "Sanofi", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US69608A1088", Address = "1200 17th Street,Floor 15,Denver, CO 80202,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Palantir Technologies Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US03831W1080", Address = "1100 Page Mill Road,Palo Alto, CA 94304,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "AppLovin Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US5738741041", Address = "1000 North West Street,Suite 1200,Wilmington, DE 19801,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Marvell Technology, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US8716071076", Address = "675 Almanor Avenue,Sunnyvale, CA 94085,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Synopsys, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US1273871087", Address = "Building 5,2655 Seely Avenue,San Jose, CA 95134,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Cadence Design Systems, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US4824801009", Address = "One Technology Drive,Milpitas, CA 95035,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "KLA Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US29444U7000", Address = "One Lagoon Drive,4th Floor,Redwood City, CA 94065-1562,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Equinix, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CA82509L1076", Address = "151 O'Connor Street,Ground floor,Ottawa, ON K2P 2L8,Canada", Country = CANADA_ISO, Currency = CurrencyType.USD, Name = "Shopify Inc.", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US5128073062", Address = "4650 Cushing Parkway,Fremont, CA 94538,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Lam Research Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US22160K1051", Address = "999 Lake Drive,Issaquah, WA 98027,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Costco Wholesale Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US17275R1023", Address = "170 West Tasman Drive,San Jose, CA 95134-1706,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Cisco Systems, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US0530151036", Address = "One ADP Boulevard,Roseland, NJ 07068,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Automatic Data Processing, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US09857L1089", Address = "800 Connecticut Avenue,Norwalk, CT 06854,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Booking Holdings Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US3755581036", Address = "333 Lakeside Drive,Foster City, CA 94404,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Gilead Sciences, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US3932221043", Address = "1811 Aksarben Drive,Omaha, NE 68106,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Green Plains Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US1405011073", Address = "8333 Douglas Avenue,Suite 1100,Dallas, TX 75225,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Capital Southwest Corporation", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US46269C1027", Address = "1750 Tysons Boulevard,Suite 1400,McLean, VA 22102,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Iridium Communications Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US31488V1070", Address = "751 Lakefront Commons,Newport News, VA 23606,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Ferguson Enterprises Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US92532F1003", Address = "50 Northern Avenue,Boston, MA 02210,United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Vertex Pharmaceuticals Incorporated", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "FR0010405431", Address = "ETF", Country = FRANCE_ISO, Currency = CurrencyType.EUR, Name = "Amundi MSCI Greece UCITS ETF Dist ", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US40051E2028", Address = "Bosque de Alisos No. 47A, 4th Floor Bosques de las Lomas, Mexico City, DF 05120, Mexico", Country = MEXICO_ISO, Currency = CurrencyType.USD, Name = "Grupo Aeroportuario del Sureste, S. A. B. de C. V.", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US3999091008", Address = "Teniente General Juan D. PerOn 430, 25th Floor, Buenos Aires, 1038, Argentina", Country = ARGENTINA_ISO, Currency = CurrencyType.USD, Name = "Grupo Financiero Galicia S.A.", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US7170811035", Address = "66 Hudson Boulevard East, New York, NY 10001-2192, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Pfizer Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US7427181091", Address = "One Procter & Gamble Plaza, Cincinnati, OH 45202, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "The Procter & Gamble Company", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US00206R1023", Address = "208 South Akard Street, Dallas, TX 75202, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "AT&T Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US9311421039", Address = "1 Customer Drive, Bentonville, AR 72716, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Walmart Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "DK0062498333", Address = "Novo Alle 1, Bagsvaerd, 2880, Denmark", Country = DENMARK_ISO, Currency = CurrencyType.DKK, Name = "Novo Nordisk A/S", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US76243J1051", Address = "222 Berkeley Street, 12th Floor, Boston, MA 02116, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Rhythm Pharmaceuticals, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US04351P1012", Address = "Tuborg Boulevard 12, Hellerup, 2900, Denmark", Country = DENMARK_ISO, Currency = CurrencyType.USD, Name = "Ascendis Pharma A/S", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "IE00B56GVS15", Address = "Connaught House, 1 Burlington Road Dublin 4, Dublin, D04 C5Y6, Ireland", Country = IRELAND_ISO, Currency = CurrencyType.USD, Name = "Alkermes plc", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "GB00B63H8491", Address = "Kings Place, 90 York Way, London, N1 9FX, United Kingdom", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.GBX, Name = "Rolls-Royce Holdings plc", TaxReductionText = "10. clen, odstavek 2a" },
                new CompanyEntity { ISIN = "US8522341036", Address = "1955 Broadway, Suite 600, Oakland, CA 94612, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Block, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US8038663006", Address = "Sasol Place, 50 Katherine Street Sandton, Johannesburg, 2196, South Africa", Country = SOUTH_AFRICA_ISO, Currency = CurrencyType.USD, Name = "Sasol Limited", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US9314271084", Address = "108 WILMOT ROAD, Deerfield, Illinois, 60015, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "WALGREENS BOOTS ALLIANCE", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US75886F1075", Address = "777 Old Saw Mill River Road, Tarrytown, NY 10591-6707, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Regeneron Pharmaceuticals, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "BMG611881019", Address = "Clarendon House, 2 Church Street, Hamilton, HM 11, Bermuda", Country = UNITED_KINGDOM_ISO, Currency = CurrencyType.USD, Name = "Liberty Global Ltd.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CA4509131088", Address = "150 King Street West, Suite 2200, Toronto, ON M5H 1J9, Canada", Country = CANADA_ISO, Currency = CurrencyType.CAD, Name = "IAMGOLD Corporation", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US87427V1035", Address = "622 Third Avenue, New York, NY 10017, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Talkspace, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US1143401024", Address = "200 Summit Drive, 6th Floor, Burlington, MA 01803, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Azenta, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "KYG1144A1058", Address = "31 Hudson Yards, 11th Floor, New York, NY 10001, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Bit Digital, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US2333774071", Address = "5301 Hollister St., Houston, TX 77040, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "DXP Enterprises, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "US3596641098", Address = "4399 Santa Anita Avenue, El Monte, CA 91731, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Fulgent Genetics, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "VGG273581030", Address = "Avenida Jujuy 2013, C1247ABI, Buenos Aires, Argentina", Country = ARGENTINA_ISO, Currency = CurrencyType.USD, Name = "Despegar.com Corp.", TaxReductionText = "" },
                new CompanyEntity { ISIN = "US83417M1045", Address = "1 HaMada Street, Herzliya Pituach, 4673335, Israel", Country = ISRAEL_ISO, Currency = CurrencyType.USD, Name = "SolarEdge Technologies, Inc.", TaxReductionText = "10. clen, odstavek 2c" },
                new CompanyEntity { ISIN = "MHY8162K2046", Address = "40 Agiou Konstantinou Street, Athens, Marousi, 15124, Greece", Country = GREECE_ISO, Currency = CurrencyType.USD, Name = "Star Bulk Carriers Corp.", TaxReductionText = "10. clen, odstavek 2" },
                new CompanyEntity { ISIN = "US0234361089", Address = "3854 American Way, Suite A, Baton Rouge, Louisiana, 70816, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Amedisys", TaxReductionText = "10. clen, odstavek 2b" },
                new CompanyEntity { ISIN = "CA68617J1003", Address = "145 King Street West, Suite #1400, Toronto, ON M5H 1J8, Canada", Country = CANADA_ISO, Currency = CurrencyType.CAD, Name = "Organigram Global Inc.", TaxReductionText = "10. clen, odstavek 2d" },
                new CompanyEntity { ISIN = "US21044C1071", Address = "290 Healthwest Drive, Suite 2, Dothan, AL 36303, United States", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "Construction Partners, Inc.", TaxReductionText = "10. clen, odstavek 2b" },
                //new CompanyEntity { ISIN = "", Address = "", Country = UNITED_STATES_ISO, Currency = CurrencyType.USD, Name = "", TaxReductionText = "" },

            ];

            companies = data.ToDictionary(data => data.ISIN, data => data);
            data = null;
        }

        public CompanyEntity GetCompany(string key) // Currently the key is the name of the company
        {
            if (companies.TryGetValue(RemoveStockTicker(key), out CompanyEntity company))
            {
                return company;
            }
            Console.WriteLine("Company " + key + " not found.");
            return new CompanyEntity { Address = "MISSING", Country = "MISSING", Currency = CurrencyType.USD, ISIN = "MISSING", Name = key, TaxReductionText = "MISSING" };
        }

        /// <summary>
        /// Removes the stock ticker from a company name.
        /// </summary>
        /// <param name="companyName">The full company name including the ticker.</param>
        /// <returns>The company name without the ticker.</returns>
        private static string RemoveStockTicker(string companyName)
        {
            int lastOpenParenIndex = companyName.LastIndexOf('(');
            int lastCloseParenIndex = companyName.LastIndexOf(')');

            // Ensure the parentheses are valid and at the end
            if (lastOpenParenIndex > 0 && lastCloseParenIndex > lastOpenParenIndex && lastCloseParenIndex == companyName.Length - 1)
            {
                return companyName.Substring(0, lastOpenParenIndex).TrimEnd();
            }
            return companyName;
        }
    }
}